language: java
jdk: oraclejdk7

deploy:
  provider: releases
  api_key:
    secure: qMXfuiHiTILfMxHtrqkdsjyX74/YXKKzjM5ej+XLv85B0td3qyT9ogu1rD97zw41UIkwsGLcvH0ZqFJ448zddC5nNDOx3M0Spi/GKbmg5xNnCuLxg1k9URnLqdGbnTbxzhO7k/R09sMFH3EmoYNRNLIvHSFG1sUqvzUJbG40d9I=
  file:
    - $TRAVIS_BUILD_DIR/build/libs/Qatja-$TRAVIS_TAG.jar
    - $TRAVIS_BUILD_DIR/build/libs/Qatja-$TRAVIS_TAG-javadoc.jar
  on:
    all_branches: true
    repo: Qatja/Qatja
    tags: true

script:
  - ./gradlew build